version: '3.7'
services:
  jenkins:
    image: yallalabs/jenkins:centos
    environment:
      #- JAVA_OPTS=-Dhudson.footerURL=http://yallalabs.com
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false -Dhudson.footerURL=http://yallalabs.com -Duser.timezone=Europe/Rome
      - JENKINS_USER=admin
      - JENKINS_PASS=CHANGE_ME
    ports:
      - 80:8080
      - 443:8443
      - 50000:50000
    volumes:
      - jenkins_data:/var/jenkins_home
    networks:
      - jenkins-net
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
         condition: on-failure
      placement:
        constraints: 
          - node.role == worker  

volumes:
  jenkins_data:
    driver: local
    driver_opts:
      type: "none"
      o: "bind"
      device: "/jenkinsdata"

networks:
  jenkins-net:
    driver: overlay
